### ISSUE TITLE
Setup Instructions

### ISSUE THREAD

**Issue by ericholscher** [chrisjsewell/rst-language-server#4]
Hey there! I love this project, but would love to figure out how to run it. I opened it in VSCode and hit F5, but it seems to want to run the file that is open, and I don't know what file that should be. I tried the `.ts` file, but got this output:

```
(readthedocs3) (readthedocs3) <Pro2016:eric> ~/checkouts/rst-language-server [git:master] 
-> cd /Users/eric/checkouts/rst-language-server ; env PYTHONIOENCODING=UTF-8 PYTHONUNBUFFERED=1 /Users/eric/.virtualenvs/readthedocs3/bin/python /Users/eric/.vscode/extensions/ms-python.python-2020.2.64397/pythonFiles/ptvsd_launcher.py --default --client --host localhost --port 63502 /Users/eric/checkouts/rst-language-server/vscode-client/src/extension.ts 
Traceback (most recent call last):
  File "/Users/eric/.vscode/extensions/ms-python.python-2020.2.64397/pythonFiles/ptvsd_launcher.py", line 48, in <module>
    main(ptvsdArgs)
  File "/Users/eric/.vscode/extensions/ms-python.python-2020.2.64397/pythonFiles/lib/python/old_ptvsd/ptvsd/__main__.py", line 432, in main
    run()
  File "/Users/eric/.vscode/extensions/ms-python.python-2020.2.64397/pythonFiles/lib/python/old_ptvsd/ptvsd/__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 261, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 236, in _get_code_from_file
    code = compile(f.read(), fname, 'exec')
  File "/Users/eric/checkouts/rst-language-server/vscode-client/src/extension.ts", line 1
    /* --------------------------------------------------------------------------------------------
    ^
```

**Comment by chrisjsewell** [comment]
Heya @ericholscher, yeh @choldgraf said you might be interested 😄 

Ermm, I don't know it just works for me lol!? Have you had a look at https://code.visualstudio.com/api/get-started/your-first-extension? This is how it was created.

`F5` should be hooked up to launch: https://github.com/chrisjsewell/rst-language-server/blob/56580d878bdaf5e07bc1d189c4472723cbaac782/.vscode/launch.json#L15

Alternatively, try launching it from the debug sidebar:

![image](https://user-images.githubusercontent.com/2997570/76006742-d964ef00-5f04-11ea-93a9-9a229f5cfb21.png)

Also, I should mention in the README that currently you need to be in a python environment where you have installed `pip install -e .[jsonrpc]`, and probably have selected that environment in the vscode settings: https://github.com/chrisjsewell/rst-language-server/blob/56580d878bdaf5e07bc1d189c4472723cbaac782/.vscode/settings.json#L16

**Comment by choldgraf** [comment]
Perhaps this is something we can put some cycles into for the EBP once the core build system is ready to go 👍

**Comment by chrisjsewell** [comment]
> Perhaps this is something we can put some cycles into for the EBP once the core build system is ready to go 👍

Oh yeh absolutely; the updates to [mistletoe-ebp](https://mistletoe-ebp.readthedocs.io) and, by extension, [MyST-Parser](https://myst-parser.readthedocs.io) are being made very much with their interoperability with an LSP in mind (source position storage, thread-safety, etc ...). This should make it easier to plug them in to this system (well certainly easier than with the docutils rST parser!)
